Move atomic_ops libs into Requires.private
ivmai/bdwgc pull request #656
Opened 2024-08-27 01:19 UTC by fundawang

Acturally, bdwgc it self may requires atomic_ops, but it does not require downstream packages (like guile) requires atomic_ops. So I would suggest that move `@ATOMIC_OPS_LIBS@` into `Requires.private`, so that won't confuse downstream packages, especially when performing check.

2024-08-27 10:01 UTC, ivmai commented
Please rebase to fresh master and explain the difference from the previous PR I just merged.

2024-08-27 11:09 UTC, ivmai requested changes

2024-08-27 11:09 UTC, ivmai commented on CMakeLists.txt
> +    set(ATOMIC_OPS_PC "atomic_ops")
Also, update comment "ATOMIC_OPS_LIBS, PACKAGE_VERSION are defined above" below

2024-08-27 11:09 UTC, ivmai commented on configure.ac
>            ATOMIC_OPS_LIBS="-latomic_ops"
Define ATOMIC_OPS_LIBS based on ATOMIC_OPS_PC value.

2024-08-27 11:09 UTC, ivmai commented on configure.ac
> +          AC_SUBST([ATOMIC_OPS_PC])],
Also define ATOMIC_OPS_PC="" below (for internal "internal" case)

2024-08-28 00:42 UTC, fundawang commented
I suddenly realized a problem. `atomic_ops` shipped `atomic_ops.pc` starting from 7.2. If `bdwgc` is built upon atomic_ops 7.1, then we should not put it in `bdwgc.pc` file, because there is no `atomic_ops.pc` at that time.

Maybe we should leave it into `Libs.private` for now, till the time of `bdwgc` relies on `atomic_ops` >= 7.2.

2024-08-29 08:21 UTC, ivmai commented
> Maybe we should leave it into Libs.private for now, till the time of bdwgc relies on atomic_ops >= 7.2.

Although, 7.1 or 7.2 is not hard-coded in bdwgc source. I agree that we could leave this change for the future - I will create the relevant issue and close this PR.

2024-08-29 08:21 UTC, closed without merging